### ISSUE TITLE
my_flutter

### ISSUE THREAD

**Issue by ghost** [ZeroJian/FlutterHybrid#1]
4.my_flutter
Flutter 开发项目

修改了这个目录下的main.dart 文件，似乎并不生效
且删掉该目录也并没有什么影响

**Comment by ZeroJian** [comment]
这是当然, 这个项目要做的不就是这个效果吗? 不需要 Flutter 开发环境, 你如果想要生效, 首先需要 Flutter 开发环境, 然后是使用 build 重新生成 Framework, 这个教程都有说的
